-- ============================================================================
-- Replace the manual `code` text column with a bigint IDENTITY (1, 2, 3, …)
-- on clientes, equipos, mantenimientos.
--
-- Behavior after this migration:
--   - `code` is auto-generated by Postgres on INSERT (no need to send it).
--   - It's UNIQUE per table.
--   - Existing rows are populated with sequential values from the implicit
--     sequence, in physical scan order (the actual numbers may not match
--     whatever text codes existed before, but they're stable from now on).
--   - The implicit sequence advances past the highest value, so future
--     inserts won't collide with existing rows.
--
-- Re-runnable: drops/recreates each `code` column. Any FK pointing at it
-- would break (none in our schema — relations are by `id`).
-- ============================================================================

-- ─── Clientes ────────────────────────────────────────────────────────────────
alter table public.clientes drop column if exists code;

alter table public.clientes
  add column code bigint generated by default as identity not null;

alter table public.clientes
  add constraint clientes_code_unique unique (code);

-- ─── Equipos ─────────────────────────────────────────────────────────────────
alter table public.equipos drop column if exists code;

alter table public.equipos
  add column code bigint generated by default as identity not null;

alter table public.equipos
  add constraint equipos_code_unique unique (code);

-- ─── Mantenimientos ──────────────────────────────────────────────────────────
alter table public.mantenimientos drop column if exists code;

alter table public.mantenimientos
  add column code bigint generated by default as identity not null;

alter table public.mantenimientos
  add constraint mantenimientos_code_unique unique (code);
